name: Main
on: 
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - production
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node_version: ["12", "14", "16", "18"]
    steps:
    - name: Krok 1
      uses: actions/checkout@v2
    - name: Krok 2
      uses: actions/setup-node@v2
      with: 
        node-version: "18.x"
        
    - name: Instalacja dependencji
      run: npm install
    - name: Uruchomienie testów
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - name: Krok 1
        uses: actions/checkout@v2
      - name: Krok 2
        uses: azure/appservice-build@v3
        with:
          platform: nodejs
          version: 18.17.0 
      - name: Wdrażanie aplikacji na Azure App Service
        uses: azure/webapps-deploy@v1
        with: 
          app-name: nodejs-app-pl1
          publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}
    
    
    
